---
title: "Discussion Meetings"
---

This page contains a general plan for the topics of the 10 discussion section meetings that will occur this quarter.

## Jan 7--9

In this discussion, we will introduce ourselves and ensure our computers are prepared for the class. This will involve checking that we have R, RStudio, tinytex, and `tidyverse` installed. See [R basics](topics/r_basics.qmd).

## Jan 14--16 and 21--23

We will form groups of 3 and work through the [data transformation exercise](topics/data_transformation.qmd).

## Jan 28--30

You should read the following paper before this discussion:

> England, Paula, Andrew Levine, and Emma Mishel. 2020. [Progress toward gender equality in the United States has slowed or stalled,](https://www.pnas.org/doi/full/10.1073/pnas.1918891117) PNAS 117(13):6990–6997.

The problem set reproduces findings from this paper. The discussion will focus on conceptual questions from the reading. The questions below are only guidelines, and your TA might have other topics to discuss.

**1.** The authors write that "change in the gender system has been deeply asymmetric." Explain this in a sentence or two to someone who hasn’t read the article.

**2.** The authors discuss cultural changes that could lead to greater equality. Propose a question that could (hypothetically) be included in the CPS-ASEC questionnaire to help answer questions about cultural changes.

::: callout-tip
If you are not sure how to word a survey question, here are some examples from the [American Time Use Survey](https://www.atusdata.org/atus-action/variables/RCVPDLV#questionnaire_text_section), [Current Population Survey](https://cps.ipums.org/cps-action/variables/PENSION#questionnaire_text_section), and [General Social Survey](https://gssdataexplorer.norc.org/variables/706/vshow).
:::

**3.** The authors discuss institutional changes that could lead to greater equality. Propose a question that could (hypothetically) be included in the CPS-ASEC questionnaire to help answer questions about institutional changes.

**4.** What was one fact presented in this paper that most surprised you?

**5.** What about the graphs in this paper is compelling? What would you improve or change if you were producing these graphs?

## Feb 4--6

Your TA will introduce the final project, which will be carried out in groups of about 5 students within your discussion section. Your TA will help you to form groups with common interest areas.

Possible topics include (but are not limited to) inequality by race or gender, trends in poverty or inequality over time, and the causal effect of education or other life experiences on subsequent outcomes. Another possibility is to form groups centered on a particular dataset, with the topic to be decided later.

All subsequent discussions are devoted to group work on the final project.

## Feb 11--13

By the end of this discussion, your group should select a dataset for the final project. If you aren't sure where to start, we suggest the options at [ipums.org](https://www.ipums.org/).

If you finish early, you are always welcome to move on to the tasks below.

## Feb 18--20

By the end of this discussion, your group should

* select an outcome variable
* define the unit of analysis (e.g., a person, a school, a state) for which that outcome variable is defined
* determine how you plan to aggregate the outcome variable across units (e.g., by a mean, median, proportion)

If you finish early, you are always welcome to move on to the tasks below.

## Feb 25--27

By the end of this discussion, your group should discuss the target population and whether you will need to use sampling weights in your analysis.

If you finish early, you are always welcome to move on to the tasks below.

## Mar 4--6

This discussion is open for your group to work on any remaining tasks to finish up your final project. Recall that PDF slides and writeup are due by 5pm on Mar 7, with one submission per group.

## Mar 11--13

Your group will present your final project in this discussion. During each presentation by a group that is not your own, you will be asked to note something you appreciated about their presentation.



