{
  "hash": "47309e62cfcd6275e97bb84f861daeaf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Confidence Intervals\"\nsubtitle: \"UCLA Soc 114\"\nformat:\n  revealjs: default # For the web slides\n  beamer: default      # To generate the PDF version\nexecute:\n  echo: true\nresources: \n  - lec04_bootstrap.pdf\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Concepts for today\n\nStatistical concepts\n\n- Sampling distribution\n- Standard error\n- Confidence interval\n- Bootstrap\n\nCoding concepts\n\n- Writing a custom function\n- Writing a for loop\n\n## Example: Mean salary of MLB players\n\nLoad data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseball <- read_csv(\"https://soc114.github.io/data/baseball.csv\") |>\n  # Keep only a few variables for simplicity\n  select(player, team, salary)\n```\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 944 x 3\n  player             team      salary\n  <chr>              <chr>      <dbl>\n1 Bumgarner, Madison Arizona 21882892\n2 Marte, Ketel       Arizona 11600000\n3 Ahmed, Nick        Arizona 10375000\n# i 941 more rows\n```\n\n\n:::\n:::\n\n\n## Example: Mean salary of MLB players\n\nTrue mean in population of all players\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbaseball |> summarize(population_mean = mean(salary))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  population_mean\n            <dbl>\n1        4965481.\n```\n\n\n:::\n:::\n\n\n## Estimate from a sample\n\n. . .\n\nDraw a sample of 10 players.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsampled_players <- baseball |> \n  slice_sample(n = 10) |>\n  print(n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 x 3\n  player          team           salary\n  <chr>           <chr>           <dbl>\n1 Tucker, Kyle    Houston       5000000\n2 Jackson, Andre  L.A. Dodgers   722500\n3 Estrada, Thairo San Francisco 2250000\n# i 7 more rows\n```\n\n\n:::\n:::\n\n\n## Estimate from a sample\n\nTake the mean among sampled players.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsampled_players <- sampled_players |> \n  summarize(sample_estimate = mean(salary)) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  sample_estimate\n            <dbl>\n1         1536510\n```\n\n\n:::\n:::\n\n\n## Many times\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-7-1.pdf)\n:::\n:::\n\n\nIf you are following, these are in [many_samples.csv](../data/many_samples.csv).\n\n::: {.cell}\n\n```{.r .cell-code}\nmany_samples <- read_csv(many_samples, \"https://soc114.github.io/data/many_samples.csv\")\n```\n:::\n\n\n\n. . .\n\nBecause each sample produces a different estimate, there is a **distribution** of different estimates across repeated samples.\n\n. . .\n\nCan you propose a summary statistic for this distribution?\n\n## Mean of the distribution\n\nAlso called the **expected value**.\n\n<!-- $$\\text{Mean}(\\text{Estimator}) = \\frac{1}{\\text{Number of Samples}}\\sum_{i=1}^n (\\text{Estimate from Sample }i)$$ -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmany_samples |>\n  summarize(estimator_mean = mean(sample_estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  estimator_mean\n           <dbl>\n1       4999932.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-10-1.pdf)\n:::\n:::\n\n\n(In practice, the mean of the distribution is unknown)\n\n## Standard Error\n\nA measure of dispersion for the distribution of sample mean estimates.\n\n<!-- $$ -->\n<!-- \\text{SE}(\\text{Estimator}) = \\sqrt{\\text{Mean}\\Bigg(\\bigg[X - \\text{Mean}(\\text{Estimator})\\bigg]^2\\Bigg)} -->\n<!-- $$ -->\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmany_samples |>\n  summarize(standard_error = sd(sample_estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  standard_error\n           <dbl>\n1       2285513.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-12-1.pdf)\n:::\n:::\n\n\n## As the sample size grows\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-13-1.pdf)\n:::\n:::\n\n\n## As the sample size grows\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-14-1.pdf)\n:::\n:::\n\n\n## As the sample size grows\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-15-1.pdf)\n:::\n:::\n\n\n## Asymptotic Normality\n\n- As the sample size gets large (asymptotic)\n- This becomes a Normal distribution\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-16-1.pdf)\n:::\n:::\n\n\n## Middle 95\\% sampling interval\n\nWe might want to summarize:\n\n- The mean of the estimator\n- A range containing the middle 95\\% of sample estimates\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-17-1.pdf)\n:::\n:::\n\n\n**Why is that hard to do with one actual sample?**\n\n## Confidence interval via the bootstrap\n\nWhat we want:\n\n1. We would want many samples: `sample_1`, `sample_2`, `sample_3`,...\n2. We estimate with each\n3. We summarize the middle 95%\n\n## Confidence interval via the bootstrap\n\nWhat we can do:\n\n1. We get only one `sample`\n     - So we simulate hypothetical `sample_sim_1`, `sample_sim_2`,...\n2. We estimate with each\n3. We summarize the middle 95%\n\n## How to generate bootstrap samples\n\nStart with your one sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsampled_players <- baseball |>\n  slice_sample(n = 100)\n```\n:::\n\n\n. . .\n\nResample $n$ players with replacement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsampled_players_bootstrap <- sampled_players |>\n  slice_sample(prop = 1, replace = TRUE)\n```\n:::\n\n\n## How to generate bootstrap samples: Example\n\nHere is a sample of 3 players:\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_small_sample <- baseball |> \n  slice_sample(n = 3) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  player                  team          salary\n  <chr>                   <chr>          <dbl>\n1 Arenado, Nolan          St. Louis   32822071\n2 Rodriguez, Christopher* L.A. Angels   740000\n3 Ward, Taylor            L.A. Angels  2750000\n```\n\n\n:::\n:::\n\n\n## How to generate bootstrap samples: Example\n\nHere is a bootstrap sample of those 3 players.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_small_sample |> \n  slice_sample(prop = 1, replace = TRUE) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  player                  team         salary\n  <chr>                   <chr>         <dbl>\n1 Rodriguez, Christopher* L.A. Angels  740000\n2 Ward, Taylor            L.A. Angels 2750000\n3 Rodriguez, Christopher* L.A. Angels  740000\n```\n\n\n:::\n:::\n\n\n## How to generate bootstrap samples: Example\n\nHere is a bootstrap sample of those 3 players.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_small_sample |> \n  slice_sample(prop = 1, replace = TRUE) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  player                  team          salary\n  <chr>                   <chr>          <dbl>\n1 Rodriguez, Christopher* L.A. Angels   740000\n2 Arenado, Nolan          St. Louis   32822071\n3 Ward, Taylor            L.A. Angels  2750000\n```\n\n\n:::\n:::\n\n\n## How to generate bootstrap samples: Example\n\nHere is a bootstrap sample of those 3 players.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_small_sample |> \n  slice_sample(prop = 1, replace = TRUE) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  player         team          salary\n  <chr>          <chr>          <dbl>\n1 Arenado, Nolan St. Louis   32822071\n2 Arenado, Nolan St. Louis   32822071\n3 Ward, Taylor   L.A. Angels  2750000\n```\n\n\n:::\n:::\n\n\n## How to generate bootstrap samples: Example\n\nHere is a bootstrap sample of those 3 players.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_small_sample |> \n  slice_sample(prop = 1, replace = TRUE) |>\n  print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 3\n  player                  team         salary\n  <chr>                   <chr>         <dbl>\n1 Ward, Taylor            L.A. Angels 2750000\n2 Rodriguez, Christopher* L.A. Angels  740000\n3 Ward, Taylor            L.A. Angels 2750000\n```\n\n\n:::\n:::\n\n\n## Coding concepts\n\nWe will analyze hundreds of bootstrap samples.\n\nWe need two coding concepts.\n\n1. How to write an `estimator` function\n2. How to write a `for` loop\n\n## How to write an `estimator` function\n\nA function (like `mean`) takes an input and returns an output. You can write your own.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator <- function(data) {\n  data |>\n    summarize(estimate = mean(salary)) |>\n    pull(estimate)\n}\n```\n:::\n\n\nThe function takes `data` and returns an estimate.\n\n::: {.cell}\n\n```{.r .cell-code}\nestimator(data = sampled_players)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4039386\n```\n\n\n:::\n:::\n\n\n## How to write a `for` loop\n\nUseful for tasks you will repeat.\n\n. . .\n\nFirst, initialize a vector to hold results.\n\n::: {.cell}\n\n```{.r .cell-code}\nvector_for_results <- rep(NA, 3)\n```\n:::\n\nThe `rep` function repeates the value `NA` 3 times.\n\n. . .\n\nSecond, loop through and fill your vector.\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (index in 1:3) {\n  vector_for_results[index] <- index\n}\n```\n:::\n\n\nSquare brackets `[]` extract an element of a vector.\n\n## Analyze 500 bootstrap samples\n\nInitialize a vector to hold the result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbootstrap_estimates <- rep(NA, times = 500)\n```\n:::\n\n\n## Analyze 500 bootstrap samples\n\nWrite a `for` loop that will repeat 500 times.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor (index in 1:500) {\n  \n  # Draw a bootstrap sample\n  bootstrap_sample <- sampled_players |>\n    slice_sample(prop = 1, replace = TRUE)\n  \n  # Construct an estimate\n  estimate_this_index <- estimator(bootstrap_sample)\n  \n  # Store that estimate\n  bootstrap_estimates[index] <- estimate_this_index\n}\n```\n:::\n\n\n## Bootstrap results\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec04_bootstrap_files/figure-beamer/unnamed-chunk-31-1.pdf)\n:::\n:::\n\n\n## Bootstrap results: Summary statistics\n\nBootstrap estimate of the standard error.\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(bootstrap_estimates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 495720.8\n```\n\n\n:::\n:::\n\n\nMiddle 95\\% of bootstrap estimates\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(x = bootstrap_estimates, prob = c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5%   97.5% \n3120228 5070844 \n```\n\n\n:::\n:::\n\n\n## Confidence interval\n\nAn interval from $\\text{lower}(\\text{sample})$ to $\\text{upper}(\\text{sample})$ with the property: across repeated samples, 95\\% of intervals constructed this way would contain the population parameter.\n\n## Confidence interval: Example\n\nMiddle 95\\% of bootstrap estimates is a confidence interval.\n\n- The true population mean salary is $4,965,481\n- Our sample mean is $4,039,386\n- Our confidence interval is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(x = bootstrap_estimates, prob = c(.025, .975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   2.5%   97.5% \n3120228 5070844 \n```\n\n\n:::\n:::\n\n\nAcross repeated samples, 95\\% of intervals constructed this way will contain the population mean salary.\n\n## Recap\n\n* Statistical concepts\n* Coding concepts\n\n## Recap: Statistical concepts\n\nStatistical concepts\n\n- Sampling distribution\n     - Cannot be directly observed. We have one sample.\n- Standard error\n     - Spread of the sampling distribution\n- Confidence interval\n     - Covers truth in 95\\% of samples\n- Bootstrap\n     - Method of constructing the CI with one sample\n\n## Recap: Coding concepts\n\n- Writing a custom function ([R4DS Ch 25](https://r4ds.hadley.nz/functions.html))\n- Writing a for loop ([R4DS Ch 27.5](https://r4ds.hadley.nz/base-R.html#for-loops))\n\n",
    "supporting": [
      "lec04_bootstrap_files/figure-beamer"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}