---
title: "Practice with sufficient adjustment sets"
format: beamer
header-includes:
  - \usepackage{tikz}
  - \usetikzlibrary{arrows,shapes.arrows,positioning,shapes,patterns,calc}
---

## DAG 1

\begin{center}
\begin{tikzpicture}
\node (x) at (0,0) {$X$};
\node (a) at (1,0) {$A$};
\node (y) at (2,0) {$Y$};
\draw[->, thick] (x) -- (a);
\draw[->, thick] (x) to[bend right] (y);
\draw[->, thick] (a) -- (y);
\end{tikzpicture}
\end{center}

* write down all backdoor paths between $A$ and $Y$
   * recall a backdoor path has the form $A\leftarrow\text{possibly other nodes and edges}\rightarrow Y$ 
* suppose we condition on nothing
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?
* suppose we condition on $X$
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?

## DAG 2

\begin{center}
\begin{tikzpicture}
\node (x) at (0,0) {$X$};
\node (a) at (1,0) {$A$};
\node (y) at (2,0) {$Y$};
\node (u) at (1.5,1) {$U$};
\draw[->, thick] (x) -- (a);
\draw[->, thick] (x) to[bend right] (y);
\draw[->, thick] (a) -- (y);
\draw[->, thick] (u) -- (a);
\draw[->, thick] (u) -- (y);
\end{tikzpicture}
\end{center}

* write down all backdoor paths between $A$ and $Y$
   * recall a backdoor path has the form $A\leftarrow\text{possibly other nodes and edges}\rightarrow Y$ 
* suppose we condition on nothing
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?
* suppose we condition on $X$
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?

## DAG 3

\begin{center}
\begin{tikzpicture}
\node (x) at (0,0) {$X$};
\node (a) at (1,0) {$A$};
\node (y) at (2,0) {$Y$};
\node (u) at (0,1) {$U$};
\draw[->, thick] (x) -- (a);
\draw[->, thick] (x) to[bend right] (y);
\draw[->, thick] (a) -- (y);
\draw[->, thick] (u) -- (x);
\draw[->, thick] (u) -- (y);
\end{tikzpicture}
\end{center}

* write down all backdoor paths between $A$ and $Y$
   * recall a backdoor path has the form $A\leftarrow\text{possibly other nodes and edges}\rightarrow Y$ 
* suppose we condition on nothing
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?
* suppose we condition on $X$
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?

## DAG 4

\begin{center}
\begin{tikzpicture}
\node (x) at (0,0) {$X$};
\node (a) at (1,0) {$A$};
\node (y) at (2,0) {$Y$};
\node (u1) at (0,1) {$U_1$};
\node (u2) at (0,-1) {$U_2$};
\draw[->, thick] (a) -- (y);
\draw[->, thick] (u1) -- (x);
\draw[->, thick] (u1) -- (a);
\draw[->, thick] (u2) -- (x);
\draw[->, thick] (u2) to[bend right] (y);
\end{tikzpicture}
\end{center}

* write down all backdoor paths between $A$ and $Y$
   * recall a backdoor path has the form $A\leftarrow\text{possibly other nodes and edges}\rightarrow Y$ 
* suppose we condition on nothing
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?
* suppose we condition on $X$
   * which backdoor paths are unblocked, if any?
   * is the causal effect of $A$ on $Y$ identified?
