---
title: "Problem Set 2: Data Transformation and Sampling"
---

**Due: 5pm on Wednesday, February 14.**

::: {.callout-note}
Want to see how you'll be evaluated? Check out the [rubric](https://docs.google.com/forms/d/e/1FAIpQLSed5nDlpx4vVcDu9Tz_2AFphUU4_ugLAw2EyF5h6124gT-bQQ/viewform?usp=sf_link)
:::

Student identifer: [type your anonymous identifier here]

- Use this [.qmd template](../assets/pset2/pset2.qmd) to complete the problem set
- In Canvas, you will upload the PDF produced by your .qmd file
- Put your identifier above, not your name! We want anonymous grading to be possible

This problem set draws on the following paper.

> England, Paula, Andrew Levine, and Emma Mishel. 2020. [Progress toward
> gender equality in the United States has slowed or
> stalled,](https://www.pnas.org/doi/full/10.1073/pnas.1918891117) PNAS
> 117(13):6990–6997.

**A note about sex and gender**. As we have discussed in class, sex typically refers to categories assigned at birth (e.g., female, male). Gender is a performed construct with many possible values: man, woman, nonbinary, etc. The measure in the CPS-ASEC is "sex," coded male or female. We will use these data to study sex disparities between those identifying as male and female. The paper at times uses "gender" to refer to this construct.

## 1. Data analysis: Existing question

**20 points.** Reproduce Figure 1 from the paper.

Visit [cps.ipums.org](https://cps.ipums.org/cps/) to download data from the 1962--2023 March Annual Social and Economic Supplement. When choosing samples, you want all samples in the "ASEC" tab and none of the samples in the "Basic Monthly" tab. Include these variables in your cart: [sex](https://cps.ipums.org/cps-action/variables/SEX), [age](https://cps.ipums.org/cps-action/variables/AGE), [asecwt](https://cps.ipums.org/cps-action/variables/ASECWT), [empstat](https://cps.ipums.org/cps-action/variables/EMPSTAT).

To reduce extract size, select cases to those ages 25--54. Before submitting your extract, we recommend changing the data format to "Stata (.dta)" so that you get value labels.

::: {.callout-tip}
Look ahead: you will later study a new outcome of your own choosing. You could add it to your cart now if you want.
:::

On your computer, analyze these data.

- filter to `asecwt > 0` (see paper footnote on p. 6995 about negative weights)
- mutate to create an `employed` variable indicating that `empstat == 10 | empstat == 12`
- mutate to convert `sex` to a factor variable using `as_factor`
- group by `sex` and `year`
- summarize the proportion employed: use `weighted.mean` to take the mean of `employed` using the weight `asecwt`

Your figure will be close but not identical to the original. Yours will include some years that the original did not. Feel free to change aesthetics of the plot, such as the words used in labels. For example, it would be more accurate to the data to label the legend "Sex" with values "Male" and "Female."

```{r, comment = F, message = F}
library(tidyverse)
library(scales)
library(haven)
```

## 2. A new outcome

**20 points.** The CPS-ASEC has numerous variables. Pick another variable of your choosing. Add it to your cart in IPUMS, and visualize how that variable has changed over time for those identifying as male and female.

As in the previous plot, year should be on the x-axis and color should represent sex. The y-axis is up to you. You can examine something like median income, proportion holding college degrees, or the 90th percentile of usual weekly work hours. You can restrict to some subset if you want, such as those who are employed.

Your answer should include

- a written statement of what you estimated: the variable you chose, any sample restrictions you made, and how you summarized that variable
- a written interpretation of what you found
- code following style conventions
- your publication-quality visualization

## 3. Conceptual questions on sampling

The Los Angeles Family and Neighborhood Study ([L.A. FANS](https://lasurvey.rand.org/design/)) was designed to study both family and neighborhood characteristics in L.A. This question is about the sample design.

The study selected a probability sample of all households in Los Angeles County in 2000. The sample was selected by a multi-stage design that first sampled Census tracts, then Census blocks within those Census tracts, then households within those blocks. At the first stage of sampling, the study oversampled Census tracts with high poverty rates. As a result, the sample is an unequal-probability sample in which poor households had higher probabilities of sample inclusion than non-poor households.

Researchers sometimes analyze L.A. FANS with a person, a household, or a Census tract as the unit of analysis. For the questions below, we will consider a household to be the unit of analysis.

**3.1 (3 points)** What is the target population?

**3.2 (3 points)** If poor households have higher probabilities of sample inclusion, which sampled households have higher weights: poor or non-poor households?

**3.3 (4 points)** Suppose a researcher estimated the poverty rate, defined as the percent of households in poverty in L.A. County in 2000. Suppose the researcher used L.A. FANS and ignored the sample weights. Would the researcher over- or under-estimate the poverty rate?

## Recap and connections to your project

This problem set discussed two datasets you may be interested in using in your final project. You accessed and downloaded the Current Population Survey at [cps.ipums.org](https://cps.ipums.org/cps/). You may also be interested in using L.A. FANS in your final project. Those data are a bit more difficult to use and are available [here](https://www.icpsr.umich.edu/web/DSDR/studies/37279#). Full documentation of the sample design is available in Section 5 of [Sastry et al. 2006](https://www.rand.org/pubs/reprints/RP1241.html#document-details).

A few skills relevant to the project were practiced in this problem set. In your project, you should clearly define your unit of analysis and target population. You should use sample weights if appropriate. And you should write readable, well-organized code that carries out your data transformation and visualization.

