---
title: "Working with data"
---

> This topic is covered on Jan 7.

Data science is a world of abundant opportunities. Over recent decades, the field has been transformed by the rapid growth of both computational power and available data. With the proliferation of new technological advances and data opportunities, a social scientist might reasonably ask: where do I begin?

Social data science begins from a place that is both philosophical and practical.

Philosophically, we as the scientists need to understand the kinds of questions that data can answer. Data cannot generally answer normative questions about what should be, but data can answer objective questions about what is. Yet we still must choose: what numbers are important to estimate? How do those numbers inform debates? The next page discusses these choices in the context of a topic in which normative and objective arguments are often conflated: inequality.

Practically, we need the tools to work with data. This course therefore begins by setting up our [computing environment]^(Your computing environment encompasses both your computer's operating system and software installed on that operating system.). Instead of using point-and-click approaches, we will analyze data by writing code. A code script is a set of sequential instructions: it tells the computer to first do this, then do that, then report a result in a chosen way. By learning to write code, you will rapidly expand the set of data science tools available to you. Perhaps more importantly, your work will become reproducible: someone else with your raw data should be able to run your code and produce exactly the same result.

The next pages discuss the philosophical questions data can answer and then walk through the steps of working with data using code.
