---
title: "Welcome to the Honors Section"
aliases:
  - "../honors.html"
page-layout: full
format:
  html:
    toc: true
---

See the [**honors section syllabus**](assets/syllabus_honors.pdf).

Any student enrolled in Soc 114 is welcome to enroll in the honors section (Soc 189 Sem 3). The honors section is graded as a separate 1.0 credit course. It is an opportunity to engage in a small creative research project and interact with the professor and peers in a seminar format.

## Our goal

Our goal in the honors section is to:

* create our own social science questions
* download actual data relevant to the questions
* use the tools of data science to produce answers
* present findings orally and in writing

## What comes next

* Week 1: Discuss how to [ask good research questions](ask_good_questions.qmd) and [access data](access_data.qmd)
* Week 2--3: [Prepare data](prepare_data.qmd) with a guided activity using `tidyverse` tools
* Week 4: Plan a possible [visualization](sketch_a_visualization.qmd) by drawing a sketch
* Week 5--6: In-class work to produce your visualization
* Week 7: Practice how to [write results](writing.qmd)
* Week 8: Plan to [present findings](presentation.qmd)
* Week 9--10: Presentations in class
