<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Models for causal inference – Social Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../topics/matching.html" rel="next">
<link href="../topics/why_model.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Social Data Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text"> </span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assets/syllabus.pdf"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../who_we_are.html"> 
<span class="menu-text">Team</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../office_hours.html"> 
<span class="menu-text">Office Hours</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://piazza.com/class/m3q7dpj6kqd2fn"> 
<span class="menu-text">Piazza</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../forms.html"> 
<span class="menu-text">Forms</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../topics/what_is_a_model.html">Inference with Models</a></li><li class="breadcrumb-item"><a href="../topics/models_for_causal.html">Models for causal inference</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../topics/working_with_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working with Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/asking_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Asking questions with data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/r_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setting up your computer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/data_transformation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data transformation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Inference Without Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Population sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/weights.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using weights</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/define_causal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Defining causal effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/exchangeability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exchangeability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/conditional_exchangeability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conditional exchangeability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/nonparametric_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nonparametric estimation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/DAGs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Directed Acyclic Graphs</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Inference with Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/what_is_a_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is a model?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/why_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Why model?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/models_for_causal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Models for causal inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matching</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Machine learning</span></span>
  </li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Discussion Meetings</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Problem Sets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pset0.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 0</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pset1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pset2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pset3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/pset4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Problem Set 4</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../assignments/project.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivating-example" id="toc-motivating-example" class="nav-link active" data-scroll-target="#motivating-example">Motivating example</a></li>
  <li><a href="#outcome-modeling" id="toc-outcome-modeling" class="nav-link" data-scroll-target="#outcome-modeling">Outcome modeling</a>
  <ul class="collapse">
  <li><a href="#model-factual-outcomes" id="toc-model-factual-outcomes" class="nav-link" data-scroll-target="#model-factual-outcomes">1) Model factual outcomes</a></li>
  <li><a href="#predict-potential-outcomes" id="toc-predict-potential-outcomes" class="nav-link" data-scroll-target="#predict-potential-outcomes">2) Predict potential outcomes</a></li>
  <li><a href="#aggregate" id="toc-aggregate" class="nav-link" data-scroll-target="#aggregate">3) Aggregate</a></li>
  </ul></li>
  <li><a href="#treatment-modeling" id="toc-treatment-modeling" class="nav-link" data-scroll-target="#treatment-modeling">Treatment modeling</a>
  <ul class="collapse">
  <li><a href="#model-treatment-probabilities" id="toc-model-treatment-probabilities" class="nav-link" data-scroll-target="#model-treatment-probabilities">1) Model treatment probabilities</a></li>
  <li><a href="#construct-weights" id="toc-construct-weights" class="nav-link" data-scroll-target="#construct-weights">2) Construct weights</a></li>
  <li><a href="#estimate-by-weighted-means" id="toc-estimate-by-weighted-means" class="nav-link" data-scroll-target="#estimate-by-weighted-means">3) Estimate by weighted means</a></li>
  </ul></li>
  <li><a href="#doubly-robust-estimation" id="toc-doubly-robust-estimation" class="nav-link" data-scroll-target="#doubly-robust-estimation">Doubly-robust estimation</a>
  <ul class="collapse">
  <li><a href="#model-outcomes-and-produce-an-initial-ate-estimate." id="toc-model-outcomes-and-produce-an-initial-ate-estimate." class="nav-link" data-scroll-target="#model-outcomes-and-produce-an-initial-ate-estimate.">1) Model outcomes and produce an initial ATE estimate.</a></li>
  <li><a href="#model-treatments-to-create-weights" id="toc-model-treatments-to-create-weights" class="nav-link" data-scroll-target="#model-treatments-to-create-weights">2) Model treatments to create weights</a></li>
  <li><a href="#estimate-the-weighted-average-error" id="toc-estimate-the-weighted-average-error" class="nav-link" data-scroll-target="#estimate-the-weighted-average-error">3) Estimate the weighted average error</a></li>
  <li><a href="#why-double-robustness" id="toc-why-double-robustness" class="nav-link" data-scroll-target="#why-double-robustness">Why double robustness?</a></li>
  </ul></li>
  <li><a href="#concluding-thoughts" id="toc-concluding-thoughts" class="nav-link" data-scroll-target="#concluding-thoughts">Concluding thoughts</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../topics/what_is_a_model.html">Inference with Models</a></li><li class="breadcrumb-item"><a href="../topics/models_for_causal.html">Models for causal inference</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Models for causal inference</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Here are slides on <a href="../slides/lec12_causal_outcome_model/lec12_causal_outcome_model.pdf">outcome modeling</a>, a quick review and then on to <a href="../slides/ipw/ipw.pdf">treatment modeling</a>, and slides (to come) on doubly-robust estimation.</p>
</blockquote>
<p>Models are useful when we need subgroup summaries but we do not observe very many units in each subgroup. This situation is common in causal inference: we assume that <span class="math inline">\(\vec{X}\)</span> is a sufficient adjustment set so that conditional exchangeability holds, and this allows us to identify the causal quantity <span class="math inline">\(\text{E}(Y^a\mid \vec{X} = \vec{x})\)</span> by the statistical quantity <span class="math inline">\(\text{E}(Y\mid A = a, \vec{X} = \vec{x})\)</span>. But that empirical quantity—the subgroup mean among those with treatment value <span class="math inline">\(a\)</span> and adjustment set value <span class="math inline">\(\vec{x}\)</span>—may be the mean of a subgroup that is unpopulated. This is especially true in practice because the adjustment set <span class="math inline">\(\vec{X}\)</span> is often most plausible when it includes many variables, leading to a curse of dimensionality and small subgroup sample sizes. For this reason, causal inference approaches that adjust for measured variables often require us to estimate the means in many subgroups that are sparsely populated.</p>
<p>This page introduces outcome models for causal inference. To run the code on this page, you will need the tidyverse.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="motivating-example" class="level2">
<h2 class="anchored" data-anchor-id="motivating-example">Motivating example</h2>
<p>To what extent does completing a four-year college degree by age 25 increase the probability of having a spouse or residential partner with a four-year college degree at age 35, among the population of U.S. residents who were ages 12–16 at the end of 1996?</p>
<p>We used this example on the <a href="../topics/why_model.html">Why Model?</a> page and will continue with it here. For those jumping in on this page, here is a refresher.</p>
<p>This causal question draws on questions in sociology and demography about assortative mating: the tendency of people with high education, income, or status to form households together<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. One reason to care about assortative mating is that it can contribute to inequality across households: if people with high earnings potential form households together, then income inequality across households will be greater than it would be if people formed households randomly.</p>
<p>Our question is causal: to what extent is the probability of marrying a four-year college graduate higher if one were hypothetically to finish a four-year degree, versus if that same person were hypothetically to not finish a college degree? But in data that exist in the world, we see only one of these two potential outcomes. The people for whom we see the outcome under a college degree are systematically different from those for whom we see the outcome under no degree: college graduates come from families with higher incomes, higher wealth, and higher parental education, for example. All of these factors may directly shape the probability of marrying a college graduate even in the absence of college. Thus, it will be important to adjust for a set of measured confounders, represented by <span class="math inline">\(\vec{X}\)</span> in our DAG.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="models_for_causal_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>By adjusting for the variables <span class="math inline">\(\vec{X}\)</span>, we block all non-causal paths between the treatment <span class="math inline">\(A\)</span> and the outcome <span class="math inline">\(Y\)</span> in the DAG. If this DAG is correct, then conditional exchangeability holds with this adjustment set: <span class="math inline">\(\{Y^1,Y^0\}\indep A \mid\vec{X}\)</span>.</p>
<p>To estimate, we use data from the <a href="https://www.bls.gov/nls/nlsy97.htm">National Longitudinal Survey of Youth 1997</a>, a probability sample of U.S. resident children who were ages 12–16 on Dec 31, 1996. The study followed these children and interviewed them every year through 2011 and then every other year after that.</p>
<p>We will analyze a simulated version of these data (<a href="../data/nlsy97_simulated.csv">nlsy97_simulated.csv</a>), which you can access with this line of code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://soc114.github.io/data/nlsy97_simulated.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Expand to learn how to get the actual data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>To access the actual data, you would need to <a href="https://nlsinfo.org/investigator/pages/register">register</a> for an account, <a href="https://nlsinfo.org/investigator/pages/login">log in</a>, upload the <a href="../code/nlsy97.NLSY97">nlsy97.NLSY97</a> tagset that identifies our variables, and then download. Unzip the folder and put the contents in a directory on your computer. Then run our code file <a href="../code/prepare_nlsy97.R">prepare_nlsy97.R</a> in that folder. This will produce a new file <code>d.RDS</code>, contains the data. You could analyze that file. In the interest of transparency, we wrote the code <a href="../data/nlsy97_simulated.R">nlsy97_simulated.R</a> to convert these real data to simulated data that we can share.</p>
</div>
</div>
</div>
<p>The data contain several variables</p>
<ul>
<li><code>id</code> is an individual identifier for each person</li>
<li><code>a</code> is the treatment, containing the respondent’s education coded <code>treated</code> if the respondent completed a four-year college degree and <code>untreated</code> if not.</li>
<li><code>y</code> is the outcome: <code>TRUE</code> if has a spouse or residential partner at age 35 who holds a college degree, and <code>FALSE</code> if no spouse or partner or if the spouse or partner at age 35 does not have a degree.</li>
<li>There are several pre-treatment variables
<ul>
<li><code>sex</code> is coded <code>Female</code> and <code>Male</code></li>
<li><code>race</code> is race/ethnicity and is coded <code>Hispanic</code>, <code>Non-Hispanic Black</code>, and <code>Non-Hispanic Non-Black</code>.</li>
<li><code>mom_educ</code> is the respondent’s mother’s education as reported in 1997. It takes the value <code>No mom</code> if the child had no residential mother in 1997, and otherwise is coded with her education: <code>&lt; HS</code>, <code>High school</code>, <code>Some college</code>, or <code>College</code>.</li>
<li><code>dad_educ</code> is the respondent’s father’s education as reported in 1997. It takes the value <code>No dad</code> if the child had no residential father in 1997, and otherwise is coded with his education: <code>&lt; HS</code>, <code>High school</code>, <code>Some college</code>, or <code>College</code>.</li>
<li><code>log_parent_income</code> is the log of gross household income in 1997</li>
<li><code>log_parent_wealth</code> is the log of household net worth in 1997</li>
<li><code>test_percentile</code> is the respondent’s percentile score on a test of math and verbal skills administered in 1999 (the Armed Services Vocational Aptitude Battery).</li>
</ul></li>
</ul>
<p>When values are missing, we have replcaed them with predicted values. In the simulated data, no row represents a real person because values have been drawn randomly from a probability distribution designed to mimic what exists in the real data. As discussed above, we did this in order to share the file with you by a download on this website.</p>
</section>
<section id="outcome-modeling" class="level2">
<h2 class="anchored" data-anchor-id="outcome-modeling">Outcome modeling</h2>
<p>Because the causal effect of <code>A</code> on <code>Y</code> is identified by adjusting for the confounders, we can estimate by outcome modeling. There are three general steps.</p>
<ol type="1">
<li>Model <span class="math inline">\(E(Y\mid A, \vec{X})\)</span>, the conditional mean of <span class="math inline">\(Y\)</span> given the treatment and confounders</li>
<li>Predict potential outcomes
<ul>
<li>set <code>A = 1</code> for every unit. Predict <span class="math inline">\(Y^1\)</span></li>
<li>set <code>A = 0</code> for every unit. Predict <span class="math inline">\(Y^0\)</span></li>
</ul></li>
<li>Aggregate to the average causal effect</li>
</ol>
<section id="model-factual-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="model-factual-outcomes">1) Model factual outcomes</h3>
<p>The code below uses Ordinary Least Squares to estimate an outcome model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>outcome_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  y <span class="sc">~</span> a <span class="sc">*</span> (</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    sex <span class="sc">+</span> race <span class="sc">+</span> mom_educ <span class="sc">+</span> dad_educ <span class="sc">+</span> log_parent_income <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>      log_parent_wealth <span class="sc">+</span> test_percentile</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>lm()</code> function estimates a linear model, which is stored in the <code>model</code> object. The first argument is the model formula, which defines the function by which we model the conditional mean of the outcome given the predictors. The second argument is the data we use to learn the model.</p>
<p>Why did we choose this model formula? You can actually choose any model formula, but there are some reasons we chose this one. In our model formula, we begin with the treatment <code>a</code> and then we interact this treatment with an additive function of all confounders <code>a * (...)</code>. This is equivalent to fitting two models: an additive OLS model for <span class="math inline">\(Y^\text{treated}\)</span> and an additive OLS model for <span class="math inline">\(Y^\text{untreated}\)</span>, which is a desirable thing to do when we think the effect of college may differ for people with different values on the adjustment set. This type of model was proposed by <a href="https://projecteuclid.org/journals/annals-of-applied-statistics/volume-7/issue-1/Agnostic-notes-on-regression-adjustments-to-experimental-data--Reexamining/10.1214/12-AOAS583.full">Lin (2013)</a> and is also known as a t-learner (<a href="https://www.pnas.org/doi/abs/10.1073/pnas.1804597116">Kunzel et al.&nbsp;2019</a>) because it is equivalent to estimating <strong>t</strong>wo separate regression models of outcome on confounder: one for the treated group and one for the untreated group. For a recent discussion of its advantages, see <a href="https://arxiv.org/pdf/2403.03299">Hazlett &amp; Shinkre (2024)</a>.</p>
<p>The model has a lot of terms! You can see them with <code>summary(model)</code>. Thankfully, we won’t interpret any of them. We will just use the model as a tool to predict potential outcomes.</p>
</section>
<section id="predict-potential-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="predict-potential-outcomes">2) Predict potential outcomes</h3>
<p>The code below predicts the conditional average potential outcome under treatment and control at the confounder values of each observation.</p>
<p>First, we create data with <code>a</code> set to the value <code>treated</code> for everyone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data_if_treated <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="st">"treated"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 10
     id a       y     sex   race             mom_educ dad_educ log_parent_income
  &lt;dbl&gt; &lt;chr&gt;   &lt;lgl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;chr&gt;    &lt;chr&gt;                &lt;dbl&gt;
1     1 treated TRUE  Male  Non-Hispanic No… &lt; HS     &lt; HS                  8.55
2     2 treated FALSE Male  Non-Hispanic No… Some co… College              31.8 
3     3 treated FALSE Male  Non-Hispanic Bl… College  High sc…             14.1 
# ℹ 7,768 more rows
# ℹ 2 more variables: log_parent_wealth &lt;dbl&gt;, test_percentile &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Then, we create data with <code>a</code> set to the value <code>untreated</code> for everyone.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data_if_untreated <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">a =</span> <span class="st">"untreated"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 10
     id a         y     sex   race           mom_educ dad_educ log_parent_income
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt; &lt;chr&gt; &lt;chr&gt;          &lt;chr&gt;    &lt;chr&gt;                &lt;dbl&gt;
1     1 untreated TRUE  Male  Non-Hispanic … &lt; HS     &lt; HS                  8.55
2     2 untreated FALSE Male  Non-Hispanic … Some co… College              31.8 
3     3 untreated FALSE Male  Non-Hispanic … College  High sc…             14.1 
# ℹ 7,768 more rows
# ℹ 2 more variables: log_parent_wealth &lt;dbl&gt;, test_percentile &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We use our outcome model to predict the conditional mean of the potential outcome under each scenario.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>predicted_outcomes <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y1_predicted =</span> <span class="fu">predict</span>(outcome_model, <span class="at">newdata =</span> data_if_treated),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y0_predicted =</span> <span class="fu">predict</span>(outcome_model, <span class="at">newdata =</span> data_if_untreated),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">effect_predicted =</span> y1_predicted <span class="sc">-</span> y0_predicted</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, a, y, y1_predicted, y0_predicted, effect_predicted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 6
     id a         y     y1_predicted y0_predicted effect_predicted
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt;        &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;
1     1 treated   TRUE         0.507        0.318            0.188
2     2 treated   FALSE        0.742        0.505            0.237
3     3 untreated FALSE        0.391        0.159            0.232
# ℹ 7,768 more rows</code></pre>
</div>
</div>
<p>In the code above, the function call <code>predict(model, newdata = data_if_treated)</code> uses the <code>model</code> object to make predictions for the data in <code>data_if_treated</code>, which contains each person coded with the treatment set to <code>treated</code>. The predicted values <code>y1_predicted</code> are predictions <span class="math inline">\(\hat{Y}^\text{treated}\)</span> of the potential outcome under a four-year college degree. Likewise, the function call <code>predict(model, newdata = data_if_untreated)</code> predicts the outcomes under no college degree. The <code>effect_predicted</code> variable contains the predicted causal effect at the adjustment set values of each person in the data.</p>
</section>
<section id="aggregate" class="level3">
<h3 class="anchored" data-anchor-id="aggregate">3) Aggregate</h3>
<p>The final step is to aggregate to an average causal effect estimate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>outcome_model_estimate <span class="ot">&lt;-</span> predicted_outcomes <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(y1_predicted, y0_predicted, effect_predicted) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(<span class="at">.funs =</span> mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  y1_predicted y0_predicted effect_predicted
         &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;
1        0.432        0.160            0.272</code></pre>
</div>
</div>
<p>We estimate that completing college increases the probability of having a college-educated by 0.272, from 0.16 to 0.432. This causal conclusion relies both on our causal assumptions (the DAG) and our statistical assumptions (the chosen model).</p>
</section>
</section>
<section id="treatment-modeling" class="level2">
<h2 class="anchored" data-anchor-id="treatment-modeling">Treatment modeling</h2>
<p>Instead of modeling the outcome, another way of using models for causal inference is to model the probability of treatment assignment. This approach is more analogous to sampling from a population.</p>
<p>In a probability sample, we observe the outcome <span class="math inline">\(Y_i\)</span> for any sampled unit <span class="math inline">\((S_i=1)\)</span> which is seen with some probability of sampling, <span class="math inline">\(P(S=1\mid\vec{X} = \vec{x}_i)\)</span> that may differ across subgroups with different values of some variables <span class="math inline">\(\vec{X}\)</span>. As discussed in population sampling, the sampling weight is the inverse of these probabilities. A person who is sampled with a 20% probability represents 1 / .2 = 5 people in the population (the other 4 being unsampled).</p>
<p>In a conditionally randomized experiment, we observe the outcome under treatment <span class="math inline">\(Y_i^1\)</span> for any treated unit <span class="math inline">\(A_i=1\)</span>, which might be assigned with some probability <span class="math inline">\(P(A_i=1\mid\vec{X} = \vec{x}_i)\)</span> that differs across subgroups defined by an adjustment set <span class="math inline">\(\vec{X}\)</span>. In a conditionally randomized experiment, these probabilities are known and the overall expected outcome under treatment <span class="math inline">\(\E(Y^1)\)</span> can be estimated by the average of the observed outcomes under treatment, weighted by the inverse probability of being treated. A treated unit who had a 20% probability of being treated represents 1 / .2 = 5 people (the other 4 being untreated).</p>
<p>In an observational study, we don’t know the probability of being treated given the variables in our sufficient adjustment set. We need to model that probability. There are three general steps.</p>
<ol type="1">
<li>Model treatment probabilities given an adjustment set</li>
<li>Construct a weight for each unit</li>
<li>Estimate by weighted means within each treatment group</li>
</ol>
<section id="model-treatment-probabilities" class="level3">
<h3 class="anchored" data-anchor-id="model-treatment-probabilities">1) Model treatment probabilities</h3>
<p>One way to model the probability of treatment is with logistic regression. If logistic regression is new to you, see the bottom of <a href="../topics/what_is_a_model.html">What is a model?</a>.</p>
<p><span class="math display">\[
\log\left(\frac{P(A = 1 \mid\vec{X})}{1-P(A = 1\mid\vec{X})}\right) = \alpha + \vec{X}'\vec\beta
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>treatment_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">I</span>(a <span class="sc">==</span> <span class="st">"treated"</span>) <span class="sc">~</span> sex <span class="sc">+</span> race <span class="sc">+</span> mom_educ <span class="sc">+</span> dad_educ <span class="sc">+</span> log_parent_income <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    log_parent_wealth <span class="sc">+</span> test_percentile,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For every unit, we can then predict the probability of being treated given the adjustment set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>predicted_treatment_probabilities <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_treated =</span> <span class="fu">predict</span>(treatment_model, <span class="at">type =</span> <span class="st">"response"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, a, y, p_treated)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 4
     id a         y     p_treated
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt;     &lt;dbl&gt;
1     1 treated   TRUE      0.236
2     2 treated   FALSE     0.860
3     3 untreated FALSE     0.133
# ℹ 7,768 more rows</code></pre>
</div>
</div>
<p>The <code>type = "response"</code> argument is essential, because this tells R to predict the probability of treatment instead of the log odds of treatment.</p>
</section>
<section id="construct-weights" class="level3">
<h3 class="anchored" data-anchor-id="construct-weights">2) Construct weights</h3>
<p>For each unit, we can construct a weight that is the inverse probability of that unit’s treatment assignment. Recall that if a unit is treated and had a 0.2 probability of treatment, then we could think of this unit as representing 1 / 0.2 = 5 units: itself and 4 others like it who were not treated. The weight on each unit is the inverse probability of the treatment value that happened for that unit.</p>
<p><span class="math display">\[
w_i = \begin{cases}
\frac{1}{\P(A = 1\mid \vec{X} = \vec{x}_i)} &amp;\text{if treated} \\
\frac{1}{1 - \P(A = 1\mid \vec{X} = \vec{x}_i)} &amp;\text{if untreated}
\end{cases}
\]</span></p>
<p>In code, we can use <code>case_when()</code> to assign this weight as <code>1 / p_treated</code> for treated units and <code>1 / (1 - p_treated)</code> for untreated units.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>inverse_probability_weights <span class="ot">&lt;-</span> predicted_treatment_probabilities <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">weight =</span> <span class="fu">case_when</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>      a <span class="sc">==</span> <span class="st">"treated"</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">/</span> p_treated,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>      a <span class="sc">==</span> <span class="st">"untreated"</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p_treated)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 5
     id a         y     p_treated weight
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1     1 treated   TRUE      0.236   4.24
2     2 treated   FALSE     0.860   1.16
3     3 untreated FALSE     0.133   1.15
# ℹ 7,768 more rows</code></pre>
</div>
</div>
</section>
<section id="estimate-by-weighted-means" class="level3">
<h3 class="anchored" data-anchor-id="estimate-by-weighted-means">3) Estimate by weighted means</h3>
<p>Finally, we use the weights to take the treated units and draw inference about what would happen to all units if they were hypothetically treated, and to use the untreated units and draw inference about what would happen to all units if they were hypothetically untreated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>inverse_probability_weights <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Within each treatment group</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(a) <span class="sc">|&gt;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Take the mean weighted by inverse probability of treatment weights</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">estimate =</span> <span class="fu">weighted.mean</span>(y, <span class="at">w =</span> weight)) <span class="sc">|&gt;</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Pivot wider and difference to estimate the effect</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> a, <span class="at">values_from =</span> estimate, <span class="at">names_prefix =</span> <span class="st">"if_"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">effect =</span> if_treated <span class="sc">-</span> if_untreated)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  if_treated if_untreated effect
       &lt;dbl&gt;        &lt;dbl&gt;  &lt;dbl&gt;
1      0.425        0.167  0.259</code></pre>
</div>
</div>
</section>
</section>
<section id="doubly-robust-estimation" class="level2">
<h2 class="anchored" data-anchor-id="doubly-robust-estimation">Doubly-robust estimation</h2>
<p>We don’t have to constrain ourselves to outcome modeling or treatment modeling. We can also use both together.</p>
<ol type="1">
<li>Model outcomes and produce an initial ATE estimate</li>
<li>Model treatment probabilities and produce inverse probability weights</li>
<li>Estimate the weighted average error of your outcome model
<ul>
<li>For each unit, calculate the error <span class="math inline">\(Y-\hat{Y}\)</span></li>
<li>Each unit represents a number of units corresponding to its inverse probability weight</li>
<li>Estimate the population-average error by the weighted mean of errors, within each treatment group</li>
</ul></li>
<li>Improve estimate (1) by subtracting the average error (3)</li>
</ol>
<p>This estimator has some properties that make it superior to outcome or treatment modeling alone, as we will discuss at the end of this section.</p>
<section id="model-outcomes-and-produce-an-initial-ate-estimate." class="level3">
<h3 class="anchored" data-anchor-id="model-outcomes-and-produce-an-initial-ate-estimate.">1) Model outcomes and produce an initial ATE estimate.</h3>
<p>We already did this above! Our predictions are stored in an object already.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>predicted_outcomes <span class="sc">|&gt;</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 6
     id a         y     y1_predicted y0_predicted effect_predicted
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt;        &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;
1     1 treated   TRUE         0.507        0.318            0.188
2     2 treated   FALSE        0.742        0.505            0.237
3     3 untreated FALSE        0.391        0.159            0.232
# ℹ 7,768 more rows</code></pre>
</div>
</div>
</section>
<section id="model-treatments-to-create-weights" class="level3">
<h3 class="anchored" data-anchor-id="model-treatments-to-create-weights">2) Model treatments to create weights</h3>
<p>We already did this above! Our weights are stored in an object already.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>inverse_probability_weights <span class="sc">|&gt;</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 5
     id a         y     p_treated weight
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1     1 treated   TRUE      0.236   4.24
2     2 treated   FALSE     0.860   1.16
3     3 untreated FALSE     0.133   1.15
# ℹ 7,768 more rows</code></pre>
</div>
</div>
</section>
<section id="estimate-the-weighted-average-error" class="level3">
<h3 class="anchored" data-anchor-id="estimate-the-weighted-average-error">3) Estimate the weighted average error</h3>
<p>For each unit, we can calculate the error as the difference between the actual outcome <span class="math inline">\(Y\)</span> and the predicted outcome <span class="math inline">\(\hat{Y}\)</span> under the treatment value that actually happened for that unit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>errors <span class="ot">&lt;-</span> predicted_outcomes <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">error =</span> <span class="fu">case_when</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>      a <span class="sc">==</span> <span class="st">"treated"</span> <span class="sc">~</span> y1_predicted <span class="sc">-</span> y,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>      a <span class="sc">==</span> <span class="st">"untreated"</span> <span class="sc">~</span> y0_predicted <span class="sc">-</span> y</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 7
     id a         y     y1_predicted y0_predicted effect_predicted  error
  &lt;dbl&gt; &lt;chr&gt;     &lt;lgl&gt;        &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;  &lt;dbl&gt;
1     1 treated   TRUE         0.507        0.318            0.188 -0.493
2     2 treated   FALSE        0.742        0.505            0.237  0.742
3     3 untreated FALSE        0.391        0.159            0.232  0.159
# ℹ 7,768 more rows</code></pre>
</div>
</div>
<p>We then merge our errors with our weights, so that we can see how many total units each error should represent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>errors_with_weight <span class="ot">&lt;-</span> errors <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, a, error) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    inverse_probability_weights <span class="sc">|&gt;</span> <span class="fu">select</span>(id, p_treated, weight), </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(id)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,771 × 5
     id a          error p_treated weight
  &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1     1 treated   -0.493     0.236   4.24
2     2 treated    0.742     0.860   1.16
3     3 untreated  0.159     0.133   1.15
# ℹ 7,768 more rows</code></pre>
</div>
</div>
<p>As a concrete example, the error when predicting the first person’s outcome was -0.493. This person’s treatment was treated, and that treatment occurred with treatment probability 0.236. Some units like this unit got treated, and others didn’t. When we take a weighted average within treatment groups to estimate the average over all people, this person’s error stands in for the errors of 4.244 units in total.</p>
<p>With our inverse probability weights, we can take the weighted average error within each treatment group as an estimate of the error that would persist if we hypothetically applied our model to all the <span class="math inline">\(Y^1\)</span> values and all the <span class="math inline">\(Y^0\)</span> values (even the ones we didn’t see).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>weighted_average_error <span class="ot">&lt;-</span> errors_with_weight <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(a) <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">average_outcome_error =</span> <span class="fu">weighted.mean</span>(error, <span class="at">w =</span> weight)) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  a         average_outcome_error
  &lt;chr&gt;                     &lt;dbl&gt;
1 treated                 0.00960
2 untreated              -0.00416</code></pre>
</div>
</div>
<p>In this case our model was very good—the weighted average errors are nearly 0! The weighted average error of (outcome under treatment) - (outcome under control) is calculated below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>weighted_average_effect_error <span class="ot">&lt;-</span> weighted_average_error <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> a, </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> average_outcome_error, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_prefix =</span> <span class="st">"average_error_"</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">effect_error =</span> average_error_treated <span class="sc">-</span> average_error_untreated) <span class="sc">|&gt;</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(effect_error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We estimate that our outcome model was mis-specified: we estimate that our outcome model estimate will be 0.014 away from the truth. We can improve our estimate by subtracting the estimated error from the original estimate.</p>
<p><span class="math display">\[
\text{Updated Estimate} = \text{Outcome Model Estimate} - \text{Estimated Error}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>updated_estimate <span class="ot">&lt;-</span> outcome_model_estimate <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">estimated_error =</span> weighted_average_effect_error) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">updated_estimate =</span> effect_predicted <span class="sc">-</span> estimated_error) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  y1_predicted y0_predicted effect_predicted estimated_error updated_estimate
         &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;
1        0.432        0.160            0.272          0.0138            0.258</code></pre>
</div>
</div>
</section>
<section id="why-double-robustness" class="level3">
<h3 class="anchored" data-anchor-id="why-double-robustness">Why double robustness?</h3>
<p>The doubly-robust estimator has a desirable property. We would like it to be the case that our estimator of the average causal effect is consistent: as the sample size grows to infinity, the estimator converges to the true average causal effect. Let <span class="math inline">\(\hat{f}()\)</span> be the estimated outcome model and <span class="math inline">\(\hat{m}()\)</span> be the estimated treatment model. The doubly-robust estimator is consistent for the average causal effect if either</p>
<ol type="1">
<li>The outcome model is consistent for the truth: <span class="math inline">\(\hat{f}(a,\vec{x})\rightarrow \text{E}(Y\mid A = a, \vec{X} = \vec{x})\)</span> for all values <span class="math inline">\(a\)</span> and <span class="math inline">\(\vec{x}\)</span> OR</li>
<li>The treatment model is consistent for the truth: <span class="math inline">\(\hat{m}(\vec{x})\rightarrow \text{P}(A = 1\mid \vec{X} = \vec{x})\)</span> where the <span class="math inline">\(\rightarrow\)</span> indicates asymptotic convergence as the sample size grows.</li>
</ol>
<p>Our estimator is good if <strong>either</strong> (1) or (2) is true! When we aren’t sure how to specify the form of our model, it is good to have two chances.</p>
<p>When both estimators are consistent, the doubly-robust estimator brings additional advantages such as a faster rate of convergence toward the truth as the sample size grows. For many statistical reasons, we should prefer the doubly robust estimator.</p>
<p>A reason to choose outcome or treatment modeling on its own is that each of these alone may be easier to implement and explain to readers than the doubly-robust estimator. When presenting complex statistical results, being able to explain the procedure to your audience is an important consideration.</p>
</section>
</section>
<section id="concluding-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="concluding-thoughts">Concluding thoughts</h2>
<p>Outcome modeling is a powerful strategy because it bridges nonparametric causal identification to longstanding strategies where outcomes are modeled by parametric regression.</p>
<p>Inverse probability of treatment weighting is a powerful strategy because it bridges nonparametric causal identification to longstanding strategies from survey sampling where units from a population are sampled with known probabilities of inclusion. The analogy is that outcomes under treatment are sampled with estimated inclusion probabilities (the probability of treatment). Just as in a population sample we would need to think carefully about the probability of sampling, treatment modeling encourages us to model the probability of receiving the observed treatment.</p>
<p>Doubly robust estimation brings the two together for an estimator that is statistically preferable, albeit conceptually more complicated!</p>


</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>For reviews, see <a href="https://doi.org/10.2307/2095670">Mare 1991</a> and <a href="https://doi.org/10.1146/annurev-soc-071312-145544">Schwartz 2013</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../topics/why_model.html" class="pagination-link" aria-label="Why model?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Why model?</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../topics/matching.html" class="pagination-link" aria-label="Matching">
        <span class="nav-page-text">Matching</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>